language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install unzip
  - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - unzip gtest-1.7.0.zip
  - export GTEST_DIR=`pwd`/gtest-1.7.0

script: make test
